# Applied Data Science Capstone

## Week 3 - Peer-graded Assignment: Segmenting and Clustering Neighborhoods in Toronto.

### Part 1 - Exploring and getting the Postal Codes from Wikipedia site

In [1]:
import pandas as pd

tables = pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M', header=0, keep_default_na=False)

headings = ['Postal Code', 'Borough', 'Neighborhood']
for table in tables:
    current_headings = table.columns.values[:3]
    if len(current_headings) != len(headings):
        continue
    if all(current_headings == headings):
        break

#table['Country name'].replace({r'.*!(.*)': r'\1'}, regex=True, inplace=True)
table[headings].to_csv('test.txt', sep=';', header=False, index=False)

In [2]:
# Renamed column titles so they are like it was asked in requirements
table.columns=['PostalCode', 'Borough', 'Neighborhood']

In [3]:
table.shape

(180, 3)

Above code imported 180 rows from the Wikipedia URL provided.

In [4]:
# Verify how many rows have Borough=Not Assigned
tableBoroughNA=table[table['Borough']=='Not assigned']
tableBoroughNA.shape

(77, 3)

In [5]:
# Drop rows that have Borough=Not Assigned
indexTable=table[table['Borough']=='Not assigned'].index
table.drop(indexTable, inplace=True)
table.reset_index(drop=True, inplace=True)
table.shape

(103, 3)

Since there were 77 rows where Borough was Not Assigned and as it was requested to ignore these Not Assigned cells, I dropped the corresponding rows.

In [6]:
table.head()

PostalCode           Borough                                 Neighborhood
0        M3A        North York                                    Parkwoods
1        M4A        North York                             Victoria Village
2        M5A  Downtown Toronto                    Regent Park, Harbourfront
3        M6A        North York             Lawrence Manor, Lawrence Heights
4        M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [7]:
# Verify if there is any row where neighborhood = Not assigned to make neighborhood=Borough
tableNeiNA=table[table['Neighborhood']=='Not assigned']
if len(tableNeiNA)==0:
    print('There is no rows where Neighborhood = Not Assigned . So... Nothing to change here.')

There is no rows where Neighborhood = Not Assigned . So... Nothing to change here.


As per above cell, there is no Neighborhood with Not Assigned to be changed by the Borough value

In [8]:
numRows=table.shape[0]
print ('My dataframe has', numRows, ' rows.')

My dataframe has 103  rows.


After all cleaning as per requirements, there are 103 rows in the data frame. 

### Part 2 - Exploring and getting the  latitude and the longitude coordinates of each neighborhood. 

In [11]:
!wget -q -O 'Geospatial_Coordinates.csv'  http://cocl.us/Geospatial_data
locCoord = pd.read_csv('Geospatial_Coordinates.csv')
locCoord.head()

'wget' is not recognized as an internal or external command,
operable program or batch file.


Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [12]:
locCoord.columns=['PostalCode','Latitude','Longitude']
locCoord.head()

PostalCode   Latitude  Longitude
0        M1B  43.806686 -79.194353
1        M1C  43.784535 -79.160497
2        M1E  43.763573 -79.188711
3        M1G  43.770992 -79.216917
4        M1H  43.773136 -79.239476

In above lines, I read the 'Geospatial_Coordinates.csv' file to get the Latitude and Longitude info from all Postal Codes.

In [13]:
table2 = pd.merge(table,
                 locCoord[['PostalCode','Latitude', 'Longitude']], sort=False,
                 on='PostalCode')
table2

PostalCode           Borough  \
0          M3A        North York   
1          M4A        North York   
2          M5A  Downtown Toronto   
3          M6A        North York   
4          M7A  Downtown Toronto   
..         ...               ...   
98         M8X         Etobicoke   
99         M4Y  Downtown Toronto   
100        M7Y      East Toronto   
101        M8Y         Etobicoke   
102        M8Z         Etobicoke   

                                          Neighborhood   Latitude  Longitude  
0                                            Parkwoods  43.753259 -79.329656  
1                                     Victoria Village  43.725882 -79.315572  
2                            Regent Park, Harbourfront  43.654260 -79.360636  
3                     Lawrence Manor, Lawrence Heights  43.718518 -79.464763  
4          Queen's Park, Ontario Provincial Government  43.662301 -79.389494  
..                                                 ...        ...        ...  
98       The Kingsway, Montgomery Road, Old Mill North  43.653654 -79.506944  
99                                Church and Wellesley  43.665860 -79.383160  
100  Business reply mail Processing Centre, South C...  43.662744 -79.321558  
101  Old Mill South, King's Mill Park, Sunnylea, Hu...  43.636258 -79.498509  
102  Mimico NW, The Queensway West, South of Bloor,...  43.628841 -79.520999  

[103 rows x 5 columns]

And... above I merged the orginal data frame (table) with the data frame created from the file with Latitude and Longitude information. 

The result was put in table2 data frame.

In [14]:
table2.shape

(103, 5)

Table2 dataframe has 103 rows with the lat and long info read from the 'Geospatial_Coordinates.csv'file.

### Part 3 - Explore and cluster the neighborhoods in Toronto

In [18]:
!pip install  folium
import folium # plotting library

import numpy as np # library to handle data in a vectorized manner

# libraries for displaying images
from IPython.display import Image 
from IPython.core.display import HTML 
    
# tranforming json file into a pandas dataframe library
from pandas.io.json import json_normalize

!pip install geopy 
from geopy.geocoders import Nominatim # module to convert an address into latitude and longitude values

print('Folium installed')
print('Libraries imported.')

Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable
Folium installed
Libraries imported.


Get Foursquare info for authentication in DEV Foursquare site

In [19]:
# Foursquare credential and version
CLIENT_ID = 'O0JRD5QQRARPTBI0UHXGAHKL1V0VJVM03J33CVTBACTZ4W41' # your Foursquare ID
CLIENT_SECRET = 'IGKCD5WQTPXRSDY2XZS11HHNJT3I0MPLKPJVLP4114SF3QMG' # your Foursquare Secret
VERSION = '20180604'

In [20]:
radius=500
LIMIT=100

Create a new dataframe with only Boroughs having Toronto

In [21]:
# Create a new dataframe to use in this part 3. This dataframe will have only rows with Toronto Boroughs. 
table3 = table2[table2['Borough'].str.contains('Toronto')]
table3

PostalCode           Borough  \
2          M5A  Downtown Toronto   
4          M7A  Downtown Toronto   
9          M5B  Downtown Toronto   
15         M5C  Downtown Toronto   
19         M4E      East Toronto   
20         M5E  Downtown Toronto   
24         M5G  Downtown Toronto   
25         M6G  Downtown Toronto   
30         M5H  Downtown Toronto   
31         M6H      West Toronto   
36         M5J  Downtown Toronto   
37         M6J      West Toronto   
41         M4K      East Toronto   
42         M5K  Downtown Toronto   
43         M6K      West Toronto   
47         M4L      East Toronto   
48         M5L  Downtown Toronto   
54         M4M      East Toronto   
61         M4N   Central Toronto   
62         M5N   Central Toronto   
67         M4P   Central Toronto   
68         M5P   Central Toronto   
69         M6P      West Toronto   
73         M4R   Central Toronto   
74         M5R   Central Toronto   
75         M6R      West Toronto   
79         M4S   Central Toronto   
80         M5S  Downtown Toronto   
81         M6S      West Toronto   
83         M4T   Central Toronto   
84         M5T  Downtown Toronto   
86         M4V   Central Toronto   
87         M5V  Downtown Toronto   
91         M4W  Downtown Toronto   
92         M5W  Downtown Toronto   
96         M4X  Downtown Toronto   
97         M5X  Downtown Toronto   
99         M4Y  Downtown Toronto   
100        M7Y      East Toronto   

                                          Neighborhood   Latitude  Longitude  
2                            Regent Park, Harbourfront  43.654260 -79.360636  
4          Queen's Park, Ontario Provincial Government  43.662301 -79.389494  
9                             Garden District, Ryerson  43.657162 -79.378937  
15                                      St. James Town  43.651494 -79.375418  
19                                         The Beaches  43.676357 -79.293031  
20                                         Berczy Park  43.644771 -79.373306  
24                                  Central Bay Street  43.657952 -79.387383  
25                                            Christie  43.669542 -79.422564  
30                            Richmond, Adelaide, King  43.650571 -79.384568  
31                        Dufferin, Dovercourt Village  43.669005 -79.442259  
36   Harbourfront East, Union Station, Toronto Islands  43.640816 -79.381752  
37                            Little Portugal, Trinity  43.647927 -79.419750  
41                        The Danforth West, Riverdale  43.679557 -79.352188  
42            Toronto Dominion Centre, Design Exchange  43.647177 -79.381576  
43        Brockton, Parkdale Village, Exhibition Place  43.636847 -79.428191  
47                      India Bazaar, The Beaches West  43.668999 -79.315572  
48                      Commerce Court, Victoria Hotel  43.648198 -79.379817  
54                                     Studio District  43.659526 -79.340923  
61                                       Lawrence Park  43.728020 -79.388790  
62                                            Roselawn  43.711695 -79.416936  
67                                    Davisville North  43.712751 -79.390197  
68     Forest Hill North & West, Forest Hill Road Park  43.696948 -79.411307  
69                       High Park, The Junction South  43.661608 -79.464763  
73                   North Toronto West, Lawrence Park  43.715383 -79.405678  
74                 The Annex, North Midtown, Yorkville  43.672710 -79.405678  
75                              Parkdale, Roncesvalles  43.648960 -79.456325  
79                                          Davisville  43.704324 -79.388790  
80                      University of Toronto, Harbord  43.662696 -79.400049  
81                                  Runnymede, Swansea  43.651571 -79.484450  
83                         Moore Park, Summerhill East  43.689574 -79.383160  
84           Kensington Market, Chinatown, Grange Park  43.653206 -79.400049  
86   Summerhill West, Rathnelly, So

Get Toronto Latitude and Longitude info to make the map

In [22]:
# Get Toronto Lat and Long info
address = 'Toronto, ON'
geolocator = Nominatim(user_agent="foursquare_agent")
location = geolocator.geocode(address)
latToronto = location.latitude
longToronto = location.longitude

print('Toronto Latitude: {}, and Longitude: {}.'.format(latToronto, longToronto))

Toronto Latitude: 43.6534817, and Longitude: -79.3839347.


#### Design the Toronto map and put the markers from table3 dataframe.

In [23]:
# Design Toronto Map with Markers
torontoMap = folium.Map(location=[latToronto, longToronto], zoom_start=10)

# put markers in the map
for lat, lng, borough, Neighborhood in zip(table3['Latitude'], table3['Longitude'], table3['Borough'], table3['Neighborhood']):
    label = '{}, {}'.format(Neighborhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(torontoMap)  
    
torontoMap

In [24]:
import requests
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

#### Get Toronto venues

In [25]:
torontoVenues = getNearbyVenues(names=table3['Neighborhood'],
                                   latitudes=table3['Latitude'],
                                   longitudes=table3['Longitude']
                                  )

Regent Park, Harbourfront
Queen's Park, Ontario Provincial Government
Garden District, Ryerson
St. James Town
The Beaches
Berczy Park
Central Bay Street
Christie
Richmond, Adelaide, King
Dufferin, Dovercourt Village
Harbourfront East, Union Station, Toronto Islands
Little Portugal, Trinity
The Danforth West, Riverdale
Toronto Dominion Centre, Design Exchange
Brockton, Parkdale Village, Exhibition Place
India Bazaar, The Beaches West
Commerce Court, Victoria Hotel
Studio District
Lawrence Park
Roselawn
Davisville North
Forest Hill North & West, Forest Hill Road Park
High Park, The Junction South
North Toronto West, Lawrence Park
The Annex, North Midtown, Yorkville
Parkdale, Roncesvalles
Davisville
University of Toronto, Harbord
Runnymede, Swansea
Moore Park, Summerhill East
Kensington Market, Chinatown, Grange Park
Summerhill West, Rathnelly, South Hill, Forest Hill SE, Deer Park
CN Tower, King and Spadina, Railway Lands, Harbourfront West, Bathurst Quay, South Niagara, Island airport
R

#### Verify the venues returned in the dataframe

In [26]:
torontoVenues.head(10)

Neighborhood  Neighborhood Latitude  Neighborhood Longitude  \
0  Regent Park, Harbourfront               43.65426              -79.360636   
1  Regent Park, Harbourfront               43.65426              -79.360636   
2  Regent Park, Harbourfront               43.65426              -79.360636   
3  Regent Park, Harbourfront               43.65426              -79.360636   
4  Regent Park, Harbourfront               43.65426              -79.360636   
5  Regent Park, Harbourfront               43.65426              -79.360636   
6  Regent Park, Harbourfront               43.65426              -79.360636   
7  Regent Park, Harbourfront               43.65426              -79.360636   
8  Regent Park, Harbourfront               43.65426              -79.360636   
9  Regent Park, Harbourfront               43.65426              -79.360636   

                              Venue  Venue Latitude  Venue Longitude  \
0                  Roselle Desserts       43.653447       -79.362017   
1                     Tandem Coffee       43.653559       -79.361809   
2                Morning Glory Cafe       43.653947       -79.361149   
3            Cooper Koo Family YMCA       43.653249       -79.358008   
4               Body Blitz Spa East       43.654735       -79.359874   
5                    Impact Kitchen       43.656369       -79.356980   
6                   Corktown Common       43.655618       -79.356211   
7                The Extension Room       43.653313       -79.359725   
8  The Distillery Historic District       43.650244       -79.359323   
9            Figs Breakfast & Lunch       43.655675       -79.364503   

         Venue Category  
0                Bakery  
1           Coffee Shop  
2        Breakfast Spot  
3   Distribution Center  
4                   Spa  
5            Restaurant  
6                  Park  
7  Gym / Fitness Center  
8         Historic Site  
9        Breakfast Spot

In [27]:
torontoVenues.shape

(1605, 7)

#### Group reesults by Neighborhood

In [28]:
torontoVenues.groupby('Neighborhood').count()

Neighborhood Latitude  \
Neighborhood                                                                
Berczy Park                                                            56   
Brockton, Parkdale Village, Exhibition Place                           23   
Business reply mail Processing Centre, South Ce...                     17   
CN Tower, King and Spadina, Railway Lands, Harb...                     15   
Central Bay Street                                                     62   
Christie                                                               17   
Church and Wellesley                                                   76   
Commerce Court, Victoria Hotel                                        100   
Davisville                                                             34   
Davisville North                                                        7   
Dufferin, Dovercourt Village                                           14   
First Canadian Place, Underground city                                100   
Forest Hill North & West, Forest Hill Road Park                         5   
Garden District, Ryerson                                              100   
Harbourfront East, Union Station, Toronto Islands                     100   
High Park, The Junction South                                          23   
India Bazaar, The Beaches West                                         20   
Kensington Market, Chinatown, Grange Park                              58   
Lawrence Park                                                           4   
Little Portugal, Trinity                                               43   
Moore Park, Summerhill East                                             3   
North Toronto West, Lawrence Park                                      23   
Parkdale, Roncesvalles                                                 14   
Queen's Park, Ontario Provincial Government                            34   
Regent Park, Harbourfront                                              48   
Richmond, Adelaide, King                                               92   
Rosedale                                                                4   
Roselawn                                                                2   
Runnymede, Swansea                                                     37   
St. James Town                                                         77   
St. James Town, Cabbagetown                                            46   
Stn A PO Boxes                                                         92   
Studio District                                                        40   
Summerhill West, Rathnelly, South Hill, Forest ...                     16   
The Annex, North Midtown, Yorkville                                    23   
The Beaches                                                             4   
The Danforth West, Riverdale                                           42   
Toronto Dominion Centre, Design Exchange                              100   
University of Toronto, Harbord                                         34   

                                                    Neighborhood Longitude  \
Neighborhood                                                                 
Berczy Park                                                             56   
Brockton, Parkdale Village, Exhibition Place                            23   
Business reply mail Processing Centre, South Ce...                      17   
CN Tower, King and Spadina, Railway Lands, Harb...                      15   
Central Bay Street                                                      62   
Christie                                                                17   
Church and Wellesley                                                    76   
Commerce Court, Victoria Hotel                                         100   
Davisville                                                              34   
Davisville North                    

#### Make neighbourhoods analysis

In [29]:
# one hot encoding
torontoOnehot = pd.get_dummies(torontoVenues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
torontoOnehot['Neighborhood'] = torontoVenues['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns = [torontoOnehot.columns[-1]] + list(torontoOnehot.columns[:-1])
torontoOnehot.head()

Afghan Restaurant  Airport  Airport Food Court  Airport Gate  \
0                  0        0                   0             0   
1                  0        0                   0             0   
2                  0        0                   0             0   
3                  0        0                   0             0   
4                  0        0                   0             0   

   Airport Lounge  Airport Service  Airport Terminal  American Restaurant  \
0               0                0                 0                    0   
1               0                0                 0                    0   
2               0                0                 0                    0   
3               0                0                 0                    0   
4               0                0                 0                    0   

   Antique Shop  Aquarium  ...  Toy / Game Store  Trail  Train Station  \
0             0         0  ...                 0      0              0   
1             0         0  ...                 0      0              0   
2             0         0  ...                 0      0              0   
3             0         0  ...                 0      0              0   
4             0         0  ...                 0      0              0   

   Vegetarian / Vegan Restaurant  Video Game Store  Vietnamese Restaurant  \
0                              0                 0                      0   
1                              0                 0                      0   
2                              0                 0                      0   
3                              0                 0                      0   
4                              0                 0                      0   

   Wine Bar  Wings Joint  Women's Store  Yoga Studio  
0         0            0              0            0  
1         0            0              0            0  
2         0            0              0            0  
3         0            0              0            0  
4         0            0              0            0  

[5 rows x 235 columns]

#### group rows by neighborhood and by taking the mean of the frequency of occurrence of each category

In [30]:
torontoGrouped = torontoOnehot.groupby('Neighborhood').mean().reset_index()
torontoGrouped

Neighborhood  Afghan Restaurant  \
0                                         Berczy Park           0.000000   
1        Brockton, Parkdale Village, Exhibition Place           0.000000   
2   Business reply mail Processing Centre, South C...           0.000000   
3   CN Tower, King and Spadina, Railway Lands, Har...           0.000000   
4                                  Central Bay Street           0.000000   
5                                            Christie           0.000000   
6                                Church and Wellesley           0.013158   
7                      Commerce Court, Victoria Hotel           0.000000   
8                                          Davisville           0.000000   
9                                    Davisville North           0.000000   
10                       Dufferin, Dovercourt Village           0.000000   
11             First Canadian Place, Underground city           0.000000   
12    Forest Hill North & West, Forest Hill Road Park           0.000000   
13                           Garden District, Ryerson           0.000000   
14  Harbourfront East, Union Station, Toronto Islands           0.000000   
15                      High Park, The Junction South           0.000000   
16                     India Bazaar, The Beaches West           0.000000   
17          Kensington Market, Chinatown, Grange Park           0.000000   
18                                      Lawrence Park           0.000000   
19                           Little Portugal, Trinity           0.000000   
20                        Moore Park, Summerhill East           0.000000   
21                  North Toronto West, Lawrence Park           0.000000   
22                             Parkdale, Roncesvalles           0.000000   
23        Queen's Park, Ontario Provincial Government           0.000000   
24                          Regent Park, Harbourfront           0.000000   
25                           Richmond, Adelaide, King           0.000000   
26                                           Rosedale           0.000000   
27                                           Roselawn           0.000000   
28                                 Runnymede, Swansea           0.000000   
29                                     St. James Town           0.000000   
30                        St. James Town, Cabbagetown           0.000000   
31                                     Stn A PO Boxes           0.000000   
32                                    Studio District           0.000000   
33  Summerhill West, Rathnelly, South Hill, Forest...           0.000000   
34                The Annex, North Midtown, Yorkville           0.000000   
35                                        The Beaches           0.000000   
36                       The Danforth West, Riverdale           0.000000   
37           Toronto Dominion Centre, Design Exchange           0.000000   
38                     University of Toronto, Harbord           0.000000   

     Airport  Airport Food Court  Airport Gate  Airport Lounge  \
0   0.000000            0.000000      0.000000        0.000000   
1   0.000000            0.000000      0.000000        0.000000   
2   0.000000            0.000000      0.000000        0.000000   
3   0.066667            0.066667      0.066667        0.133333   
4   0.000000            0.000000      0.000000        0.000000   
5   0.000000            0.000000      0.000000        0.000000   
6   0.000000            0.000000      0.000000        0.000000   
7   0.000000            0.000000      0.000000        0.000000   
8   0.000000            0.000000      0.000000        0.000000   
9   0.000000            0.000000      0.000000        0.000000   
10  0.000000            0.000000      0.000000        0.000000   
11  0.000000            0.000000      0.000000        0.000000   
12  0.000000            0.000000      0.000000        0.000000   
13  0.000000            0.000000      0.000000        0.000000   
14  0.0000

#### Print each neighborhood with themost common venues

In [31]:
num_top_venues = 6

for hood in torontoGrouped['Neighborhood']:
    print("----"+hood+"----")
    temp = torontoGrouped[torontoGrouped['Neighborhood'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')
    
print('Done !')    

----Berczy Park----
                venue  freq
0         Coffee Shop  0.07
1        Cocktail Bar  0.05
2                Café  0.04
3         Cheese Shop  0.04
4  Seafood Restaurant  0.04
5            Beer Bar  0.04


----Brockton, Parkdale Village, Exhibition Place----
            venue  freq
0            Café  0.13
1     Coffee Shop  0.09
2  Breakfast Spot  0.09
3       Nightclub  0.09
4   Grocery Store  0.04
5   Burrito Place  0.04


----Business reply mail Processing Centre, South Central Letter Processing Plant Toronto----
           venue  freq
0    Yoga Studio  0.06
1  Auto Workshop  0.06
2     Comic Shop  0.06
3    Pizza Place  0.06
4     Restaurant  0.06
5     Skate Park  0.06


----CN Tower, King and Spadina, Railway Lands, Harbourfront West, Bathurst Quay, South Niagara, Island airport----
                venue  freq
0      Airport Lounge  0.13
1     Airport Service  0.13
2    Airport Terminal  0.13
3         Coffee Shop  0.07
4  Airport Food Court  0.07
5        Airport Gat

#### Put results in a pandas dataframe

In [32]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [35]:


import numpy as np
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Neighborhood'] = torontoGrouped['Neighborhood']

for ind in np.arange(torontoGrouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(torontoGrouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted.head()

Neighborhood 1st Most Common Venue  \
0                                        Berczy Park           Coffee Shop   
1       Brockton, Parkdale Village, Exhibition Place                  Café   
2  Business reply mail Processing Centre, South C...           Yoga Studio   
3  CN Tower, King and Spadina, Railway Lands, Har...        Airport Lounge   
4                                 Central Bay Street           Coffee Shop   

  2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
0          Cocktail Bar                  Café              Beer Bar   
1        Breakfast Spot             Nightclub           Coffee Shop   
2           Pizza Place            Smoke Shop               Brewery   
3       Airport Service      Airport Terminal       Harbor / Marina   
4    Italian Restaurant        Sandwich Place                  Café   

  5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
0                Bakery    Seafood Restaurant           Cheese Shop   
1          Climbing Gym         Burrito Place    Italian Restaurant   
2                   Spa         Burrito Place        Farmers Market   
3      Sculpture Garden           Coffee Shop         Boat or Ferry   
4          Burger Joint        Ice Cream Shop   Japanese Restaurant   

  8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
0            Restaurant                   Pub         Farmers Market  
1          Intersection               Stadium             Restaurant  
2  Fast Food Restaurant            Restaurant     Light Rail Station  
3              Boutique                   Bar           Airport Gate  
4       Thai Restaurant                   Bar        Bubble Tea Shop

#### Cluster Neighborhoods

In [39]:
! pip install  sklearn
from sklearn.cluster import KMeans

# set number of clusters
kclusters = 5

torontoGrouped_clustering = torontoGrouped.drop('Neighborhood', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(torontoGrouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_ 
# to change use .astype()

Defaulting to user installation because normal site-packages is not writeable
Using legacy setup.py install for sklearn, since package 'wheel' is not installed.
    Running setup.py install for sklearn: started
    Running setup.py install for sklearn: finished with status 'done'


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 3, 0, 1, 0,
       0, 0, 0, 0, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
# add clustering labels
neighborhoods_venues_sorted.insert(0, 'Cluster_Labels', kmeans.labels_)

toronto_merged = table3

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
toronto_merged = toronto_merged.join(neighborhoods_venues_sorted.set_index('Neighborhood'), on='Neighborhood')

toronto_merged.head() # check the last columns!

ValueError: cannot insert Cluster_Labels, already exists

In [46]:
toronto_merged.head(103)

PostalCode           Borough  \
2          M5A  Downtown Toronto   
4          M7A  Downtown Toronto   
9          M5B  Downtown Toronto   
15         M5C  Downtown Toronto   
19         M4E      East Toronto   
20         M5E  Downtown Toronto   
24         M5G  Downtown Toronto   
25         M6G  Downtown Toronto   
30         M5H  Downtown Toronto   
31         M6H      West Toronto   
36         M5J  Downtown Toronto   
37         M6J      West Toronto   
41         M4K      East Toronto   
42         M5K  Downtown Toronto   
43         M6K      West Toronto   
47         M4L      East Toronto   
48         M5L  Downtown Toronto   
54         M4M      East Toronto   
61         M4N   Central Toronto   
62         M5N   Central Toronto   
67         M4P   Central Toronto   
68         M5P   Central Toronto   
69         M6P      West Toronto   
73         M4R   Central Toronto   
74         M5R   Central Toronto   
75         M6R      West Toronto   
79         M4S   Central Toronto   
80         M5S  Downtown Toronto   
81         M6S      West Toronto   
83         M4T   Central Toronto   
84         M5T  Downtown Toronto   
86         M4V   Central Toronto   
87         M5V  Downtown Toronto   
91         M4W  Downtown Toronto   
92         M5W  Downtown Toronto   
96         M4X  Downtown Toronto   
97         M5X  Downtown Toronto   
99         M4Y  Downtown Toronto   
100        M7Y      East Toronto   

                                          Neighborhood   Latitude  Longitude  \
2                            Regent Park, Harbourfront  43.654260 -79.360636   
4          Queen's Park, Ontario Provincial Government  43.662301 -79.389494   
9                             Garden District, Ryerson  43.657162 -79.378937   
15                                      St. James Town  43.651494 -79.375418   
19                                         The Beaches  43.676357 -79.293031   
20                                         Berczy Park  43.644771 -79.373306   
24                                  Central Bay Street  43.657952 -79.387383   
25                                            Christie  43.669542 -79.422564   
30                            Richmond, Adelaide, King  43.650571 -79.384568   
31                        Dufferin, Dovercourt Village  43.669005 -79.442259   
36   Harbourfront East, Union Station, Toronto Islands  43.640816 -79.381752   
37                            Little Portugal, Trinity  43.647927 -79.419750   
41                        The Danforth West, Riverdale  43.679557 -79.352188   
42            Toronto Dominion Centre, Design Exchange  43.647177 -79.381576   
43        Brockton, Parkdale Village, Exhibition Place  43.636847 -79.428191   
47                      India Bazaar, The Beaches West  43.668999 -79.315572   
48                      Commerce Court, Victoria Hotel  43.648198 -79.379817   
54                                     Studio District  43.659526 -79.340923   
61                                       Lawrence Park  43.728020 -79.388790   
62                                            Roselawn  43.711695 -79.416936   
67                                    Davisville North  43.712751 -79.390197   
68     Forest Hill North & West, Forest Hill Road Park  43.696948 -79.411307   
69                       High Park, The Junction South  43.661608 -79.464763   
73                   North Toronto West, Lawrence Park  43.715383 -79.405678   
74                 The Annex, North Midtown, Yorkville  43.672710 -79.405678   
75                              Parkdale, Roncesvalles  43.648960 -79.456325   
79                                          Davisville  43.704324 -79.388790   
80                      University of Toronto, Harbord  43.662696 -79.400049   
81                                  Runnymede, Swansea  43.651571 -79.484450   
83                         Moore Park, Summerhill East  43.689574 -79.383160   
84           Kensington Market, Chinatown, Grange Park  43.653206 -79.400049   
86 

In [47]:
toronto_merged.shape

(39, 16)

In [48]:
toronto_merged=toronto_merged.dropna()

In [49]:
toronto_merged.shape

(39, 16)

In [50]:
toronto_merged['Cluster_Labels'] = toronto_merged.Cluster_Labels.astype(int)

In [60]:
toronto_merged.head(5)

PostalCode           Borough                                 Neighborhood  \
2         M5A  Downtown Toronto                    Regent Park, Harbourfront   
4         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government   
9         M5B  Downtown Toronto                     Garden District, Ryerson   
15        M5C  Downtown Toronto                               St. James Town   
19        M4E      East Toronto                                  The Beaches   

     Latitude  Longitude  Cluster_Labels 1st Most Common Venue  \
2   43.654260 -79.360636               0           Coffee Shop   
4   43.662301 -79.389494               0           Coffee Shop   
9   43.657162 -79.378937               0        Clothing Store   
15  43.651494 -79.375418               0                  Café   
19  43.676357 -79.293031               0                 Trail   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
2                 Bakery                  Park                   Pub   
4            Yoga Studio           Music Venue              Beer Bar   
9            Coffee Shop            Restaurant        Cosmetics Shop   
15           Coffee Shop          Cocktail Bar             Gastropub   
19                   Pub     Health Food Store   Distribution Center   

        5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
2                     Theater        Breakfast Spot                  Café   
4               Smoothie Shop        Sandwich Place         Burrito Place   
9   Middle Eastern Restaurant   Japanese Restaurant    Italian Restaurant   
15        American Restaurant    Italian Restaurant            Restaurant   
19           Department Store          Dessert Shop    Dim Sum Restaurant   

   8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
2             Restaurant                   Spa         Ice Cream Shop  
4                   Café    College Auditorium      College Cafeteria  
9        Bubble Tea Shop                  Café       Ramen Restaurant  
15              Beer Bar        Clothing Store    Moroccan Restaurant  
19                 Diner        Discount Store            Yoga Studio

#### Examine clusters

In [64]:
toronto_merged.loc[toronto_merged['Cluster_Labels'] == 0, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Cluster_Labels 1st Most Common Venue  \
2    Downtown Toronto               0           Coffee Shop   
4    Downtown Toronto               0           Coffee Shop   
9    Downtown Toronto               0        Clothing Store   
15   Downtown Toronto               0                  Café   
19       East Toronto               0                 Trail   
20   Downtown Toronto               0           Coffee Shop   
24   Downtown Toronto               0           Coffee Shop   
25   Downtown Toronto               0         Grocery Store   
30   Downtown Toronto               0           Coffee Shop   
31       West Toronto               0                Bakery   
36   Downtown Toronto               0           Coffee Shop   
37       West Toronto               0                   Bar   
41       East Toronto               0      Greek Restaurant   
42   Downtown Toronto               0           Coffee Shop   
43       West Toronto               0                  Café   
47       East Toronto               0  Fast Food Restaurant   
48   Downtown Toronto               0           Coffee Shop   
54       East Toronto               0                  Café   
67    Central Toronto               0                  Park   
69       West Toronto               0       Thai Restaurant   
73    Central Toronto               0        Clothing Store   
74    Central Toronto               0        Sandwich Place   
75       West Toronto               0             Gift Shop   
79    Central Toronto               0          Dessert Shop   
80   Downtown Toronto               0                  Café   
81       West Toronto               0           Coffee Shop   
84   Downtown Toronto               0                  Café   
86    Central Toronto               0                   Pub   
87   Downtown Toronto               0        Airport Lounge   
92   Downtown Toronto               0           Coffee Shop   
96   Downtown Toronto               0                  Café   
97   Downtown Toronto               0           Coffee Shop   
99   Downtown Toronto               0           Coffee Shop   
100      East Toronto               0           Yoga Studio   

    2nd Most Common Venue 3rd Most Common Venue  \
2                  Bakery                  Park   
4             Yoga Studio           Music Venue   
9             Coffee Shop            Restaurant   
15            Coffee Shop          Cocktail Bar   
19                    Pub     Health Food Store   
20           Cocktail Bar                  Café   
24     Italian Restaurant        Sandwich Place   
25                   Café                  Park   
30                   Café            Restaurant   
31               Pharmacy           Music Venue   
36               Aquarium                  Café   
37       Asian Restaurant            Restaurant   
41            Coffee Shop    Italian Restaurant   
42                   Café                 Hotel   
43         Breakfast Spot             Nightclub   
47             Steakhouse         Burrito Place   
48                   Café            Restaurant   
54            Coffee Shop             Gastropub   
67                  Hotel                   Gym   
69     Mexican Restaurant                Bakery   
73            Coffee Shop            Shoe Store   
74                   Café           Coffee Shop   
75         Breakfast Spot               Dog Run   
79         Sandwich Place           Coffee Shop   
80                 Bakery                   Bar   
81                   Café           Pizza Place   
84                 Bakery    Mexican Restaurant   
86            Coffee Shop            Bagel Shop   
87        Airport Service      Airport Terminal   
92                   Café            Restaurant   
96            Coffee Shop            Restaurant   
97                   Café                   Gym   
99    Japanese Restaurant      Sushi Restaurant   
100           Pizza Place            Smoke Shop   

             4th Most 

In [65]:
toronto_merged.loc[toronto_merged['Cluster_Labels'] == 1, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Cluster_Labels 1st Most Common Venue  \
83  Central Toronto               1            Playground   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
83           Summer Camp            Restaurant           Yoga Studio   

   5th Most Common Venue        6th Most Common Venue 7th Most Common Venue  \
83          Dance Studio  Eastern European Restaurant            Donut Shop   

   8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
83      Doner Restaurant               Dog Run    Distribution Center

In [66]:
toronto_merged.loc[toronto_merged['Cluster_Labels'] == 2, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]


Borough  Cluster_Labels 1st Most Common Venue  \
62  Central Toronto               2          Home Service   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
62                Garden           Yoga Studio         Deli / Bodega   

   5th Most Common Venue 6th Most Common Venue        7th Most Common Venue  \
62  Ethiopian Restaurant     Electronics Store  Eastern European Restaurant   

   8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
62            Donut Shop      Doner Restaurant                Dog Run

In [67]:
toronto_merged.loc[toronto_merged['Cluster_Labels'] == 3, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Cluster_Labels 1st Most Common Venue  \
61  Central Toronto               3                  Park   
68  Central Toronto               3                  Park   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
61    Dim Sum Restaurant              Bus Line           Swim School   
68         Jewelry Store                 Trail              Bus Line   

   5th Most Common Venue 6th Most Common Venue        7th Most Common Venue  \
61           Event Space     Electronics Store  Eastern European Restaurant   
68      Sushi Restaurant           Yoga Studio             Department Store   

          8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
61                   Donut Shop      Doner Restaurant                Dog Run  
68  Eastern European Restaurant            Donut Shop       Doner Restaurant

In [68]:
toronto_merged.loc[toronto_merged['Cluster_Labels'] == 4, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Cluster_Labels 1st Most Common Venue  \
91  Downtown Toronto               4                  Park   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
91            Playground                 Trail          Cupcake Shop   

          5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
91  Eastern European Restaurant            Donut Shop      Doner Restaurant   

   8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
91               Dog Run   Distribution Center         Discount Store

### As per above information I understood that cluster 0 has most part of venues.